### ISSUE TITLE
how to filter and such things

### ISSUE THREAD

**Issue by sascha1337** [dicefm/express-crudify-mongoose#1]
do you have a example for filtering or building querys? 
mainly trying to use this lib combined with https://github.com/marmelab/ng-admin

**Comment by KATT** [comment]
Hey @sascha1337!

Apologies, I have completely missed this issue!

All code regarding to building queries is in here: https://github.com/KATT/express-crudify-mongoose/blob/master/src/lib/build-query.js. As you can see I've _started_ on pagination and have simple `.where`.

If you want to filter result you can do a query like `GET /users?name=Alex` which will do a simple query of finding all users with `name === 'Alex'`.

Essentially, it's still very limited what you can to do. 

What type of querying do you need? I can probably build it all pretty quickly.

**Comment by sascha1337** [comment]
didnt look in the source, now i have a clue whats going on, i see skip and limit is working already yes?
i try to implement this library into ng-admin. maybe the documentation needs some info about this features in the future ;-)

The next days i will look into it and tell you what query exactly needed

**Comment by KATT** [comment]
I've added some more operations + [docs](https://github.com/KATT/express-crudify-mongoose/blob/master/README.md) now. 

Let me know if you need assistance with anything. :)
